### PR TITLE
6503_pg_heron: frontend vunerabilities

### PR DESCRIPTION
**Pull request by siddharthsatyakam**

### CODE REVIEW

**Comment by nihr43** [comment]
this title and description don't communicate what these changes are or why they were made.
ticket?
testing?

**Comment by siddharthsatyakam** [comment]
In response to https://github.com/kumc-bmi/mi-docker/pull/194#discussion_r1073792264

**Comment by siddharthsatyakam** [comment]
> this title and description don't communicate what these changes are or why they were made. ticket? testing?

All changes for ecomplaince_lookup are merged to groovy during the working on 6503_pg_heron(i.e. muskie and walleye); and the latest groovy testing is running on the muskie from blackfin front-end(i.e. https://nightheron.kumc.edu:8888/heron):

Build: https://yellowfin:8443/view/i2b2_middle/job/i2b2-middletier-build/1812/console

Deploy: https://yellowfin:8443/view/i2b2_middle/job/i2b2-middletier-deploy_pg/296/console

Working i2b2: https://nightheron.kumc.edu:8888/heron/

**Comment by lav-patel** [comment]
This PR is mostly related to this PR https://github.com/kumc-bmi/studyTeam/pull/1/files

**Comment by siddharthsatyakam** [comment]
> This PR is mostly related to this PR https://github.com/kumc-bmi/studyTeam/pull/1/files

Yes that would be exact

**Review by lav-patel — APPROVED** [review]

**Pull request merged**
